# Generated by Django 3.2.7 on 2022-07-03 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=253)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('attachment', models.FileField(upload_to='productivity')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_tag_author', to=settings.AUTH_USER_MODEL)),
                ('idea_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_tag_idea_giver', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tag_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTagAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('On Review', 'On Review'), ('Nominated for Presentation', 'Nominated for Presentation'), ('Nominated for Award', 'Nominated for Award')], max_length=50)),
                ('comments', models.TextField()),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opportunity_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_tag', to='productivity.opportunitytag')),
            ],
        ),
    ]
