# Generated by Django 3.2.7 on 2022-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitytag',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='productivity'),
        ),
    ]
