# Generated by Django 3.2.7 on 2022-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_observationtag_observationtagadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtag',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='productivity/Observation Tag'),
        ),
    ]
