# Generated by Django 3.2.7 on 2022-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_alter_observationtag_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtag',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='productivity'),
        ),
        migrations.AlterField(
            model_name='observationtag',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='observationtag',
            name='observation_date',
            field=models.DateField(),
        ),
    ]
