# Generated by Django 3.2.7 on 2022-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_auto_20220717_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtag',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
