# Generated by Django 3.2.7 on 2022-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='is_hr',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_hr',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
