# Generated by Django 3.2.7 on 2022-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220707_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
