# Generated by Django 3.2.7 on 2022-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220707_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='is_productivity_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_productivity_admin',
            field=models.BooleanField(default=False),
        ),
    ]
