# Generated by Django 3.2.7 on 2022-07-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220717_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sign',
        ),
    ]
