# Generated by Django 3.2.7 on 2024-07-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240714_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.floor'),
        ),
    ]
