# Generated by Django 3.2.7 on 2024-11-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20241130_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='hod_access_relation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.hodaccess'),
        ),
        migrations.AddField(
            model_name='hodaccess',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_access_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hod_access_relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_relation', to='users.hodaccess'),
        ),
    ]
