# Generated by Django 3.2.7 on 2024-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20241130_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='hod_access_relation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hod_access_relation',
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_departments',
            field=models.ManyToManyField(related_name='hod_departments', to='users.Department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_locations',
            field=models.ManyToManyField(related_name='hod_locations', to='users.Location'),
        ),
        migrations.DeleteModel(
            name='HODAccess',
        ),
    ]
