# Generated by Django 3.2.7 on 2024-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20241130_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='permission_departments',
            new_name='hod_permission_departments',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='permission_locations',
            new_name='hod_permission_locations',
        ),
        migrations.AddField(
            model_name='profile',
            name='recom_permission_departments',
            field=models.ManyToManyField(related_name='recom_departments', to='users.Department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recom_permission_locations',
            field=models.ManyToManyField(related_name='recom_locations', to='users.Location'),
        ),
    ]
