# Generated by Django 3.2.7 on 2024-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20241210_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='emp_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hod_permission_departments',
            field=models.ManyToManyField(blank=True, related_name='hod_profiles', to='users.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hod_permission_locations',
            field=models.ManyToManyField(blank=True, related_name='hod_profiles', to='users.Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recom_permission_departments',
            field=models.ManyToManyField(blank=True, related_name='recom_profiles', to='users.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recom_permission_locations',
            field=models.ManyToManyField(blank=True, related_name='recom_profiles', to='users.Location'),
        ),
    ]
