# Generated by Django 3.2.7 on 2024-12-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20241212_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id']},
        ),
    ]
