# Generated by Django 3.1.7 on 2021-04-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=50)),
                ('instrument_id', models.CharField(max_length=30)),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommended_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_li', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanInstrumentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('confirmed', 'Confirm by HOD'), ('not_confirmed', 'Not Confirm by HOD')], default='Confirm by HOD', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('laninstrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_sign', to='connectivity.laninstrument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanInstrumentIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan', models.IntegerField(default=0)),
                ('current_switch_name', models.CharField(max_length=30)),
                ('current_port', models.IntegerField(default=0)),
                ('required_switch_name', models.CharField(default='N/A', max_length=20)),
                ('required_port', models.IntegerField(default=0)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laninstrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_it', to='connectivity.laninstrument')),
            ],
        ),
    ]
