# Generated by Django 3.1.7 on 2021-04-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0002_laninstrument_laninstrumentit_laninstrumentsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laninstrumentit',
            name='laninstrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_it', to='connectivity.laninstrument'),
        ),
        migrations.AlterField(
            model_name='laninstrumentsign',
            name='laninstrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_sign', to='connectivity.laninstrument'),
        ),
    ]
