# Generated by Django 3.1.7 on 2021-04-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0004_internet_internetsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('permission_type', multiselectfield.db.fields.MultiSelectField(choices=[('administrative_permission', 'Administrative Permission (Computer Login with Admin)'), ('usb_access_permission', 'USB Access Permission (To get access Pendrive and Storage Devices)')], max_length=100)),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommended_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_permission', to=settings.AUTH_USER_MODEL)),
                ('recommended_hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hr_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('confirmed_hod', 'Recommended by HOD'), ('confirmed_hr', 'Approved By HR'), ('confirmed_it', 'Confirmed By IT Admin')], default='Recommended by HOD', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_sign', to='connectivity.permission')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
