# Generated by Django 3.1.7 on 2021-04-08 22:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0005_permission_permissionsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.FilePathField(max_length=250), size=None)),
                ('revoke_access', django.contrib.postgres.fields.ArrayField(base_field=models.FilePathField(max_length=250), null=True, size=None)),
                ('computer_name', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('permission_type', models.CharField(choices=[('modify', 'Modify'), ('read_only', 'Read-Only')], max_length=10)),
                ('location_in_other_department', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommended_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_file', to=settings.AUTH_USER_MODEL)),
                ('recommended_hod_other_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_other', to=settings.AUTH_USER_MODEL)),
                ('recommended_hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hr_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileAccessSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('confirmed_hod', 'Recommended by HOD'), ('confirmed_hr', 'Approved By HR'), ('confirmed_hod_other_dept', 'Approved By Other Dept. Head'), ('confirmed_it', 'Confirmed By IT Admin')], default='Recommended by HOD', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('fileaccess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileaccess_sign', to='connectivity.fileaccess')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
