# Generated by Django 3.1.7 on 2021-04-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0006_fileaccess_fileaccesssign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccess',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='fileaccess',
            name='ip_address',
        ),
    ]
