# Generated by Django 3.1.7 on 2021-04-09 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0008_auto_20210408_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='revoke_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), null=True, size=None),
        ),
    ]
