# Generated by Django 3.1.7 on 2021-04-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0009_auto_20210409_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccess',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fileaccess',
            name='revoke_access',
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='location_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='revoke_access_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
