# Generated by Django 3.1.7 on 2021-07-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0012_auto_20210704_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccess',
            name='location_name',
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='location_link',
            field=models.JSONField(default='N/A'),
            preserve_default=False,
        ),
    ]
