# Generated by Django 3.1.7 on 2021-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0013_auto_20210706_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccess',
            old_name='location_link',
            new_name='dufiles_link',
        ),
    ]
