# Generated by Django 3.1.7 on 2021-07-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0015_auto_20210708_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('fileaccess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='connectivity.fileaccess')),
            ],
        ),
    ]
