# Generated by Django 3.1.7 on 2021-07-25 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0016_filelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccess',
            name='location_in_other_department',
        ),
        migrations.RemoveField(
            model_name='fileaccess',
            name='permission_type',
        ),
        migrations.RemoveField(
            model_name='fileaccess',
            name='recommended_hr',
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='recommended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='revoke_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filelink',
            name='location_in_other_department',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='filelink',
            name='permission_type',
            field=models.CharField(choices=[('modify', 'Modify'), ('read_only', 'Read-Only')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileaccesssign',
            name='sign_type',
            field=models.CharField(choices=[('confirmed_by', 'Recommended by'), ('confirmed_hod', 'Approved By HOD'), ('confirmed_hod_other_dept', 'Approved By Other Dept. Head'), ('confirmed_it', 'Confirmed By IT Admin')], default='Recommended by HOD', max_length=50),
        ),
    ]
