# Generated by Django 3.1.7 on 2021-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0017_auto_20210725_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesssign',
            name='sign_type',
            field=models.CharField(choices=[('confirmed_by', 'Recommended by'), ('confirmed_hod', 'Approved By HOD'), ('confirmed_hod_other_dept', 'Approved By Other Dept. Head'), ('confirmed_it', 'Confirmed By IT Admin')], default='Recommended by', max_length=50),
        ),
    ]
