# Generated by Django 3.1.7 on 2021-07-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0019_requisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='hms_No',
            new_name='hms_no',
        ),
    ]
