# Generated by Django 3.1.7 on 2021-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0020_auto_20210728_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='hms_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='pr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
