# Generated by Django 3.1.7 on 2021-08-07 12:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0021_auto_20210728_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('confirmed_by', 'Recommended by'), ('confirmed_hod', 'Approved By HOD'), ('confirmed_hr', 'Approved By HR'), ('confirmed_hod_it', 'Confirmed By HOD IT ')], default='Recommended by', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_sign', to='connectivity.requisition')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', ckeditor.fields.RichTextField()),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_products', to='connectivity.requisition')),
            ],
        ),
    ]
