# Generated by Django 3.2.7 on 2021-10-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0023_os_switch_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestit',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.os'),
        ),
        migrations.AlterField(
            model_name='lanrequestit',
            name='switch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.switch'),
        ),
        migrations.AlterField(
            model_name='lanrequestit',
            name='vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.vlan'),
        ),
    ]
