# Generated by Django 3.2.7 on 2021-10-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0024_auto_20211011_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestit',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connectivity.os'),
        ),
        migrations.AlterField(
            model_name='lanrequestit',
            name='switch_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='connectivity.switch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lanrequestit',
            name='vlan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='connectivity.vlan'),
            preserve_default=False,
        ),
    ]
