# Generated by Django 3.2.7 on 2021-10-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0026_auto_20211011_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestit',
            name='computer_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lanrequestit',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
