# Generated by Django 3.2.7 on 2021-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0027_auto_20211012_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lantransfersign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=15),
        ),
    ]
