# Generated by Django 3.2.7 on 2021-10-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0030_lan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lan',
        ),
    ]
