# Generated by Django 3.2.7 on 2021-10-13 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0031_delete_lan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_name', models.CharField(max_length=50)),
                ('computer_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan', models.IntegerField(default=0)),
                ('switch_port', models.IntegerField(blank=True, default=0, null=True)),
                ('cable_tag', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('cpu_model', models.CharField(blank=True, default='N/A', max_length=40, null=True)),
                ('printer_model', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('scanner_model', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.os')),
                ('switch_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.switch')),
            ],
        ),
    ]
