# Generated by Django 3.2.7 on 2021-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0032_lan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lan',
            old_name='date_signed',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='lan_name',
        ),
        migrations.AddField(
            model_name='lan',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lan',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
