# Generated by Django 3.2.7 on 2021-10-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0034_auto_20211014_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestit',
            name='required_ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanrequest_ip', to='connectivity.lan'),
        ),
    ]
