# Generated by Django 3.2.7 on 2021-10-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0035_alter_lanrequestit_required_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lantransferit',
            name='current_port',
        ),
        migrations.RemoveField(
            model_name='lantransferit',
            name='current_switch_name',
        ),
        migrations.RemoveField(
            model_name='lantransferit',
            name='provide_ip_address',
        ),
        migrations.RemoveField(
            model_name='lantransferit',
            name='required_port',
        ),
        migrations.RemoveField(
            model_name='lantransferit',
            name='required_switch_name',
        ),
        migrations.RemoveField(
            model_name='lantransferit',
            name='vlan',
        ),
        migrations.AddField(
            model_name='lantransferit',
            name='required_ip_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_ip', to='connectivity.lan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lantransferit',
            name='lantransfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_it', to='connectivity.lantransfer'),
        ),
    ]
