# Generated by Django 3.2.7 on 2021-10-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0036_auto_20211015_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanTransferIT',
        ),
    ]
