# Generated by Django 3.2.7 on 2021-10-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0037_delete_lantransferit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lantransfer',
            name='transfer_location_old_IP',
        ),
    ]
