# Generated by Django 3.2.7 on 2021-10-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0039_remove_lantransfer_current_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lantransfer',
            name='current_ip_address',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_ip', to='connectivity.lan'),
            preserve_default=False,
        ),
    ]
