# Generated by Django 3.2.7 on 2021-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0040_lantransfer_current_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetsign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'agreed'), ('disagreed', 'Disagreed')], default='Recommended by HOD', max_length=50),
        ),
        migrations.AlterField(
            model_name='permissionsign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'agreed'), ('disagreed', 'Disagreed')], default='Recommended by HOD', max_length=50),
        ),
    ]
