# Generated by Django 3.2.7 on 2021-12-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0041_auto_20211202_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestsign',
            name='lanrequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lanrequest_sign', to='connectivity.lanrequest'),
        ),
    ]
