# Generated by Django 3.2.7 on 2021-12-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0044_lantransferit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laninstrumentsign',
            name='laninstrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_sign', to='connectivity.laninstrument'),
        ),
        migrations.AlterField(
            model_name='laninstrumentsign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=15),
        ),
    ]
