# Generated by Django 3.2.7 on 2021-12-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0045_auto_20211209_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='current_port',
        ),
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='current_switch_name',
        ),
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='provide_ip_address',
        ),
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='required_port',
        ),
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='required_switch_name',
        ),
        migrations.RemoveField(
            model_name='laninstrumentit',
            name='vlan',
        ),
        migrations.AddField(
            model_name='laninstrumentit',
            name='required_ip_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_ip', to='connectivity.lan'),
            preserve_default=False,
        ),
    ]
