# Generated by Django 3.2.7 on 2021-12-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0046_auto_20211209_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laninstrumentit',
            old_name='date_signed',
            new_name='date_signed2',
        ),
    ]
