# Generated by Django 3.2.7 on 2021-12-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0047_rename_date_signed_laninstrumentit_date_signed2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laninstrumentit',
            old_name='date_signed2',
            new_name='date_signed',
        ),
    ]
