# Generated by Django 3.2.7 on 2021-12-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0048_rename_date_signed2_laninstrumentit_date_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laninstrumentit',
            name='laninstrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laninstrument_it', to='connectivity.laninstrument'),
        ),
    ]
