# Generated by Django 3.2.7 on 2021-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0050_cpumodel_printermodel_scannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallan',
            name='printer_model',
            field=models.CharField(blank=True, default='N/A', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicallan',
            name='scanner_model',
            field=models.CharField(blank=True, default='N/A', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lan',
            name='printer_model',
            field=models.CharField(blank=True, default='N/A', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lan',
            name='scanner_model',
            field=models.CharField(blank=True, default='N/A', max_length=40, null=True),
        ),
    ]
