# Generated by Django 3.2.7 on 2021-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0051_auto_20211212_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CPUModel',
            new_name='CentralProcessingUnit',
        ),
        migrations.RemoveField(
            model_name='historicallan',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='historicallan',
            name='printer_model',
        ),
        migrations.RemoveField(
            model_name='historicallan',
            name='scanner_model',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='printer_model',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='scanner_model',
        ),
    ]
