# Generated by Django 3.2.7 on 2021-12-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0052_auto_20211212_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallan',
            name='cpu_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='connectivity.centralprocessingunit'),
        ),
        migrations.AddField(
            model_name='historicallan',
            name='printer_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='connectivity.printermodel'),
        ),
        migrations.AddField(
            model_name='historicallan',
            name='scanner_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='connectivity.scannermodel'),
        ),
        migrations.AddField(
            model_name='lan',
            name='cpu_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.centralprocessingunit'),
        ),
        migrations.AddField(
            model_name='lan',
            name='printer_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.printermodel'),
        ),
        migrations.AddField(
            model_name='lan',
            name='scanner_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.scannermodel'),
        ),
    ]
