# Generated by Django 3.2.7 on 2021-12-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
        ('connectivity', '0053_auto_20211212_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='lantransfer',
            name='new_floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.floor'),
        ),
        migrations.AddField(
            model_name='lantransfer',
            name='new_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
    ]
