# Generated by Django 3.2.7 on 2021-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0054_auto_20211212_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lantransfer',
            name='transfer_location_plant',
        ),
    ]
