# Generated by Django 3.2.7 on 2021-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0057_auto_20211213_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesssign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
        migrations.AlterField(
            model_name='permissionsign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
    ]
