# Generated by Django 3.2.7 on 2021-12-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0058_auto_20211220_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallan',
            name='ip_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lan',
            name='ip_used',
            field=models.BooleanField(default=True),
        ),
    ]
