# Generated by Django 3.2.7 on 2021-12-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0059_auto_20211220_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileaccess',
            options={'verbose_name_plural': 'File Server Access FORM'},
        ),
        migrations.AlterModelOptions(
            name='internet',
            options={'verbose_name_plural': 'Internet Activation FORM'},
        ),
        migrations.AlterModelOptions(
            name='lan',
            options={'verbose_name_plural': 'Network Section'},
        ),
        migrations.AlterModelOptions(
            name='laninstrument',
            options={'verbose_name_plural': 'Lan (Instrument) Request FORM'},
        ),
        migrations.AlterModelOptions(
            name='lanrequest',
            options={'verbose_name_plural': 'Lan Request FORM'},
        ),
        migrations.AlterModelOptions(
            name='lantransfer',
            options={'verbose_name_plural': 'Lan Transfer FORM'},
        ),
        migrations.AlterModelOptions(
            name='lantransfersign',
            options={'verbose_name_plural': 'Lan Transfer FORM'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'USB Permission FORM'},
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name_plural': 'IT Requision FORM'},
        ),
    ]
