# Generated by Django 3.2.7 on 2021-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0060_auto_20211221_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelink',
            name='location_in_other_department',
        ),
        migrations.AddField(
            model_name='filelink',
            name='location',
            field=models.CharField(choices=[('other', 'Other'), ('self', 'Self')], default='other', max_length=10),
            preserve_default=False,
        ),
    ]
