# Generated by Django 3.2.7 on 2022-01-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0061_auto_20211229_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionproducts',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='requisitionsign',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='requisitionsign',
            name='signer',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.DeleteModel(
            name='RequisitionProducts',
        ),
        migrations.DeleteModel(
            name='RequisitionSign',
        ),
    ]
