# Generated by Django 3.2.7 on 2022-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0062_auto_20220104_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanrequestsign',
            name='sign_type',
            field=models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
    ]
