# Generated by Django 3.2.7 on 2022-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0063_alter_lanrequestsign_sign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanrequestsign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
