# Generated by Django 3.2.7 on 2022-07-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0064_lanrequestsign_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanrequest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lanrequestit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lanrequestsign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
