# Generated by Django 3.2.7 on 2022-07-14 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0065_auto_20220713_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanTransferHOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanTransferHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lantransfer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lantransferit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='LanTransferSign',
        ),
        migrations.AddField(
            model_name='lantransferhr',
            name='lantransfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_hr', to='connectivity.lantransfer'),
        ),
        migrations.AddField(
            model_name='lantransferhr',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lantransferhod',
            name='lantransfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_hod', to='connectivity.lantransfer'),
        ),
        migrations.AddField(
            model_name='lantransferhod',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
