# Generated by Django 3.2.7 on 2022-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0067_auto_20220714_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='laninstrumentsign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
