# Generated by Django 3.2.7 on 2022-07-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0070_auto_20220717_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionhod',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_hod', to='connectivity.permission'),
        ),
    ]
