# Generated by Django 3.2.7 on 2022-07-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0071_alter_permissionhod_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileaccesssign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileaccesssign',
            name='fileaccess',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fileaccess_sign', to='connectivity.fileaccess'),
        ),
        migrations.AlterField(
            model_name='fileaccesssign',
            name='sign_type',
            field=models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
        migrations.AlterField(
            model_name='filelink',
            name='permission_type',
            field=models.CharField(choices=[('Modify', 'Modify'), ('Read-Only', 'Read-Only')], max_length=10),
        ),
    ]
