# Generated by Django 3.2.7 on 2022-07-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0072_auto_20220717_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccesssign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='FileAccessOtherHOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fileaccess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fileaccess_other_hod', to='connectivity.fileaccess')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileAccessIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fileaccess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fileaccess_it', to='connectivity.fileaccess')),
            ],
        ),
        migrations.CreateModel(
            name='FileAccessHOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fileaccess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fileaccess_hod', to='connectivity.fileaccess')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
