# Generated by Django 3.2.7 on 2022-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0073_auto_20220717_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallan',
            name='ip_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lan',
            name='ip_used',
            field=models.BooleanField(default=False),
        ),
    ]
