# Generated by Django 3.2.7 on 2022-08-22 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20220728_0952'),
        ('connectivity', '0074_auto_20220820_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallan',
            name='floor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.floor', verbose_name='Lan Floor'),
        ),
        migrations.AddField(
            model_name='historicallan',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.location', verbose_name='Lan Location'),
        ),
        migrations.AddField(
            model_name='historicallan',
            name='used_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Lan User'),
        ),
        migrations.AddField(
            model_name='lan',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.floor', verbose_name='Lan Floor'),
        ),
        migrations.AddField(
            model_name='lan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location', verbose_name='Lan Location'),
        ),
        migrations.AddField(
            model_name='lan',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lan_user', to=settings.AUTH_USER_MODEL, verbose_name='Lan User'),
        ),
    ]
