# Generated by Django 3.2.7 on 2022-08-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0077_auto_20220828_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lan',
            options={'verbose_name_plural': 'Network Inventory Section'},
        ),
        migrations.RemoveField(
            model_name='lantransfer',
            name='transfer_IT_equipment_list',
        ),
    ]
