# Generated by Django 3.2.7 on 2022-08-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0068_alter_inventory_attachment'),
        ('connectivity', '0078_auto_20220828_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfer_user', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfer', to='hardware.inventory')),
                ('lantransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_inventory', to='connectivity.lan')),
            ],
            options={
                'verbose_name_plural': 'Lan Transfer FORM',
            },
        ),
    ]
