# Generated by Django 3.2.7 on 2022-08-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0079_inventorytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransfer',
            name='lantransfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_inventory', to='connectivity.lantransfer'),
        ),
    ]
