# Generated by Django 3.2.7 on 2022-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0068_alter_inventory_attachment'),
        ('connectivity', '0082_alter_inventorytransfer_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lantransfer',
            name='transfer_list',
            field=models.ManyToManyField(to='hardware.Inventory'),
        ),
    ]
