# Generated by Django 3.2.7 on 2022-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0068_alter_inventory_attachment'),
        ('connectivity', '0083_lantransfer_transfer_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lantransfer',
            name='transfer_list',
            field=models.ManyToManyField(blank=True, null=True, to='hardware.Inventory'),
        ),
    ]
