# Generated by Django 3.2.7 on 2022-09-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0084_alter_lantransfer_transfer_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryTransfer',
        ),
    ]
