# Generated by Django 3.2.7 on 2024-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0085_delete_inventorytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='location',
            field=models.CharField(choices=[('other', 'Other Dept.'), ('self', 'Self Dept.')], max_length=10),
        ),
    ]
