# Generated by Django 3.2.7 on 2024-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0096_alter_requisition_author'),
        ('connectivity', '0086_alter_filelink_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lantransfer',
            options={'verbose_name_plural': 'Lan Transfer Form'},
        ),
        migrations.AlterField(
            model_name='lantransfer',
            name='transfer_list',
            field=models.ManyToManyField(blank=True, to='hardware.Inventory'),
        ),
    ]
