# Generated by Django 3.2.7 on 2024-09-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_floor'),
        ('connectivity', '0088_alter_lantransfer_transfer_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='lantransfer',
            name='new_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='lantransfer',
            name='transferee_location_old_ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_lan_transfers', to='connectivity.lan'),
        ),
    ]
