# Generated by Django 3.2.7 on 2024-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0099_auto_20240901_0924'),
        ('connectivity', '0089_auto_20240901_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lantransfer',
            name='transfer_list',
            field=models.ManyToManyField(to='hardware.Product'),
        ),
    ]
