# Generated by Django 3.2.7 on 2024-09-03 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0090_alter_lantransfer_transfer_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lantransfer',
            name='recommended_hr',
        ),
        migrations.AddField(
            model_name='lantransfer',
            name='recommended_hr',
            field=models.ManyToManyField(blank=True, related_name='recommended_hr_lt', to=settings.AUTH_USER_MODEL, verbose_name='Approved HR'),
        ),
    ]
