# Generated by Django 3.2.7 on 2024-09-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0099_auto_20240901_0924'),
        ('users', '0017_alter_profile_floor'),
        ('connectivity', '0091_auto_20240903_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanTransferInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_transfer', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_current_department', to='users.department')),
                ('current_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_current_floor', to='users.floor')),
                ('current_ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lantransferinstrument_ip', to='connectivity.lan')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_current_location', to='users.location')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_new_department', to='users.department')),
                ('new_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_new_floor', to='users.floor')),
                ('new_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_new_location', to='users.location')),
                ('recommended_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lantransferinstrument_hod', to=settings.AUTH_USER_MODEL)),
                ('recommended_hr', models.ManyToManyField(blank=True, related_name='lantransferinstrument_hr', to=settings.AUTH_USER_MODEL, verbose_name='Approved HR')),
                ('transfer_list', models.ManyToManyField(to='hardware.Product')),
            ],
            options={
                'verbose_name_plural': 'Lan Instrument Transfer Form',
            },
        ),
        migrations.CreateModel(
            name='LanTransferInstrumentIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lantransfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_it', to='connectivity.lantransferinstrument')),
            ],
        ),
        migrations.CreateModel(
            name='LanTransferInstrumentHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lantransfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_hr', to='connectivity.lantransferinstrument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanTransferInstrumentHOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lantransfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lantransfer_hod', to='connectivity.lantransferinstrument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
