# Generated by Django 3.2.7 on 2024-09-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0092_lantransferinstrument_lantransferinstrumenthod_lantransferinstrumenthr_lantransferinstrumentit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lantransferinstrument',
            name='transfer_list',
        ),
    ]
