# Generated by Django 3.2.7 on 2024-09-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connectivity', '0093_remove_lantransferinstrument_transfer_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lantransferinstrument',
            options={'verbose_name_plural': 'Lan Instrument Transfer Forms'},
        ),
        migrations.AlterField(
            model_name='lantransferinstrument',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
