# Generated by Django 3.2.7 on 2024-09-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0095_lantransferinstrument_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lantransferinstrumentit',
            name='required_ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lan_ip', to='connectivity.lan'),
        ),
        migrations.AlterField(
            model_name='lantransferinstrumentit',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lantransferinstrumentit',
            name='lantransfer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='laninstrumenttransfer_it', to='connectivity.lantransferinstrument'),
        ),
    ]
