# Generated by Django 3.2.7 on 2024-12-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0097_alter_os_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='os',
            options={'ordering': ['id']},
        ),
    ]
