# Generated by Django 3.2.7 on 2024-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0099_auto_20241214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
