# Generated by Django 3.2.7 on 2024-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0100_alter_switch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={},
        ),
    ]
