# Generated by Django 3.2.7 on 2024-12-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0103_historicalfileaccess_historicalfileaccesshod_historicalfileaccessit_historicalfileaccessotherhod_his'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileaccess',
            options={'verbose_name_plural': 'File Server Access'},
        ),
        migrations.AlterModelOptions(
            name='laninstrument',
            options={'verbose_name_plural': 'Instrument LAN Connectivity'},
        ),
        migrations.AlterModelOptions(
            name='lanrequest',
            options={'verbose_name_plural': 'Computer LAN Connectivity'},
        ),
        migrations.AlterModelOptions(
            name='lantransfer',
            options={'verbose_name_plural': 'Computer LAN Transfer'},
        ),
        migrations.AlterModelOptions(
            name='lantransferinstrument',
            options={'verbose_name_plural': 'Instrument LAN Transfer'},
        ),
    ]
