# Generated by Django 3.2.7 on 2022-08-20 08:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informatix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftplan',
            name='fri',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='mon',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='sat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='sun',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='thu',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='tue',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftplan',
            name='wed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G', 'G'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('On-Call', 'On-Call'), ('Day-Off', 'Day-Off')], max_length=20),
        ),
    ]
