# Generated by Django 3.2.7 on 2022-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatix', '0002_auto_20220820_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
