# Generated by Django 3.2.7 on 2025-02-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informatix', '0003_roster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='February', max_length=9),
        ),
        migrations.AddField(
            model_name='roster',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_rosters', to=settings.AUTH_USER_MODEL),
        ),
    ]
