# Generated by Django 3.2.7 on 2022-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Model'),
        ),
    ]
