# Generated by Django 3.2.7 on 2022-01-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0003_alter_productmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('requisition_type', models.CharField(choices=[('new', 'New'), ('repair', 'Repair')], max_length=50, verbose_name='Requisition Type')),
                ('requisition_no', models.CharField(max_length=100, verbose_name='Requisition No')),
                ('cost_center', models.CharField(max_length=100, verbose_name='Cost Center')),
                ('hms_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='HMS No')),
                ('pr_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='P.R No')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommended_accountant', models.ForeignKey(blank=True, help_text='For Asset No assign a person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_accountant_requistion', to=settings.AUTH_USER_MODEL, verbose_name='Recommended Accountant')),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_requisition', to=settings.AUTH_USER_MODEL, verbose_name='Recommended By')),
                ('recommended_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_requisition', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HOD')),
                ('recommended_hod_it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_it_requisition', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HOD of IT')),
                ('recommended_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hr_requisition', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HR')),
            ],
            options={
                'verbose_name_plural': 'IT Requision FORM',
            },
        ),
    ]
