# Generated by Django 3.2.7 on 2022-01-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_auto_20220105_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='asset_no',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='asset_provider',
        ),
    ]
