# Generated by Django 3.2.7 on 2022-01-06 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0007_requisitionasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('confirmed', 'Confirm by HOD'), ('not_confirmed', 'Not Confirm by HOD')], default='Confirm by HOD', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_sign', to='hardware.requisition')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
