# Generated by Django 3.2.7 on 2022-01-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_requisitionsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionsign',
            name='sign_type',
            field=models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
    ]
