# Generated by Django 3.2.7 on 2022-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_quantityunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
