# Generated by Django 3.2.7 on 2022-01-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_alter_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='chalan_no',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='requisition_condition',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='rqn_no',
        ),
    ]
