# Generated by Django 3.2.7 on 2022-01-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_auto_20220112_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='hms_no',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='pr_no',
        ),
    ]
