# Generated by Django 3.2.7 on 2022-02-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_alter_requisition_recommended_accountant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.productmodel'),
        ),
    ]
