# Generated by Django 3.2.7 on 2022-02-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0022_auto_20220215_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='cost_center_fk',
        ),
    ]
