# Generated by Django 3.2.7 on 2022-02-15 13:34

from django.db import migrations


def fill_cost_center_fk(apps, schema_editor):
  Requisition = apps.get_model('hardware', 'Requisition')
  CostCenter = apps.get_model('hardware', 'CostCenter')
  for requisition in Requisition.objects.all():
    requisition.cost_center_fk, created = CostCenter.objects.get_or_create(name=requisition.cost_center)
    requisition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0024_requisition_cost_center_fk'),
    ]

    operations = [
        migrations.RunPython(fill_cost_center_fk),
    ]
