# Generated by Django 3.2.7 on 2022-02-15 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0025_auto_20220215_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='cost_center',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='cost_center_fk',
            new_name='cost_center',
        ),
    ]
