# Generated by Django 3.2.7 on 2022-02-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0026_auto_20220215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.costcenter', verbose_name='Cost Center'),
        ),
    ]
