# Generated by Django 3.2.7 on 2022-03-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0028_historicalphone_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalphone',
            name='provided_ip',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='provided_ip',
        ),
    ]
