# Generated by Django 3.2.7 on 2022-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0031_auto_20220306_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphone',
            name='emp_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='emp_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Employee ID'),
        ),
    ]
