# Generated by Django 3.2.7 on 2022-03-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
        ('hardware', '0032_auto_20220306_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphone',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.department'),
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='phone',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
