# Generated by Django 3.2.7 on 2022-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0033_auto_20220306_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphone',
            name='switch_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='switch_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
