# Generated by Django 3.2.7 on 2022-03-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
        ('hardware', '0035_auto_20220306_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalphone',
            name='location',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='location',
        ),
        migrations.AddField(
            model_name='historicalphone',
            name='floor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.floor'),
        ),
        migrations.AddField(
            model_name='phone',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.floor'),
        ),
    ]
