# Generated by Django 3.2.7 on 2022-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0037_auto_20220308_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphone',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.phonemodel'),
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.phonemodel'),
        ),
    ]
