# Generated by Django 3.2.7 on 2022-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0038_auto_20220308_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphone',
            name='switch_port',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Switch Port'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='switch_port',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Switch Port'),
        ),
    ]
