# Generated by Django 3.2.7 on 2022-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0039_auto_20220309_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='is_asset',
            field=models.BooleanField(default=False, verbose_name='Is Asset No Required ?'),
        ),
    ]
