# Generated by Django 3.2.7 on 2022-07-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0040_requisition_is_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionasset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requisitionsign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='requisitionsign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requisitionsign',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_sign', to='hardware.requisition'),
        ),
    ]
