# Generated by Django 3.2.7 on 2022-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0042_requisitioncheck_requisitionhod_requisitionhodit_requisitionhr_requisitionit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionit',
            old_name='signer',
            new_name='admin',
        ),
    ]
