# Generated by Django 3.2.7 on 2022-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0044_remove_requisition_is_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_condition',
            field=models.CharField(choices=[('Requisition Raised', 'Requisition Raised'), ('Sent to CHQ', 'Sent to CHQ'), ('In Stock', 'In Stock'), ('Delivery', 'Delivery')], default='Requisition Raised', max_length=50, verbose_name='Product Condition'),
        ),
    ]
