# Generated by Django 3.2.7 on 2022-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0047_historicalinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory',
            name='rqn_no',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='rqn_no',
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
    ]
