# Generated by Django 3.2.7 on 2022-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0049_auto_20220820_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphone',
            name='phone_condition',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('In Used', 'In Used'), ('Repair', 'Repair'), ('Decommission', 'Decommission'), ('Not Used', 'Not Used')], default='Reserved', max_length=50, verbose_name='Phone Condition'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_condition',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('In Used', 'In Used'), ('Repair', 'Repair'), ('Decommission', 'Decommission'), ('Not Used', 'Not Used')], default='Reserved', max_length=50, verbose_name='Phone Condition'),
        ),
    ]
