# Generated by Django 3.2.7 on 2022-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0052_auto_20220824_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='chalan_copy',
            field=models.FileField(blank=True, null=True, upload_to='chalan', verbose_name='Chalan Hard Copy'),
        ),
    ]
