# Generated by Django 3.2.7 on 2022-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0056_auto_20220824_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventory',
            name='chalan_copy',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Chalan Hard Copy'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='chalan_copy',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='chalan copy', verbose_name='Chalan Hard Copy'),
        ),
    ]
