# Generated by Django 3.2.7 on 2022-08-24 12:33

from django.db import migrations, models
import hardware.models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0058_alter_inventory_chalan_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityunit',
            name='chalan_copy',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=hardware.models.user_directory_path, verbose_name='Chalan Hard Copy'),
        ),
    ]
