# Generated by Django 3.2.7 on 2022-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0059_quantityunit_chalan_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantityunit',
            name='chalan_copy',
        ),
        migrations.AddField(
            model_name='quantityunit',
            name='test',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='test', verbose_name='Chalan Hard Copy'),
        ),
    ]
