# Generated by Django 3.2.7 on 2022-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0060_auto_20220824_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory',
            name='chalan_copy',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='chalan_copy',
        ),
        migrations.RemoveField(
            model_name='quantityunit',
            name='test',
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Chalan Hard Copy'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chalan', verbose_name='Chalan Hard Copy'),
        ),
    ]
