# Generated by Django 3.2.7 on 2022-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0061_auto_20220824_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='productivity', verbose_name='Chalan Hard Copy'),
        ),
    ]
