# Generated by Django 3.2.7 on 2022-08-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0063_alter_inventory_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphone',
            name='share_mode',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, verbose_name='Sharing Mode'),
        ),
        migrations.AddField(
            model_name='phone',
            name='share_mode',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=50, verbose_name='Sharing Mode'),
        ),
    ]
