# Generated by Django 3.2.7 on 2022-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0065_auto_20220825_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphone',
            name='share_mode',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=50, null=True, verbose_name='Sharing Mode'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='share_mode',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=50, null=True, verbose_name='Sharing Mode'),
        ),
    ]
