# Generated by Django 3.2.7 on 2022-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0067_alter_inventory_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='inventory', verbose_name='Chalan Hard Copy'),
        ),
    ]
