# Generated by Django 3.2.7 on 2022-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0068_alter_inventory_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan', models.CharField(max_length=50)),
                ('copy', models.FileField(blank=True, null=True, upload_to='test', verbose_name='Chalan Hard Copy')),
            ],
        ),
    ]
