# Generated by Django 3.2.7 on 2022-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0069_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Test Upload'},
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='attachment',
            field=models.TextField(default='default.jpg', max_length=100, verbose_name='Chalan Hard Copy'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='attachment',
            field=models.FileField(default='default.jpg', upload_to='inventory', verbose_name='Chalan Hard Copy'),
        ),
    ]
