# Generated by Django 3.2.7 on 2024-05-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0072_requisition_new_asset_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='recommended_accountant',
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='date_of_last_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Last Issue'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_of_last_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Last Issue'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hr_requisition', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HR (if Required)'),
        ),
    ]
