# Generated by Django 3.2.7 on 2024-06-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240603_0927'),
        ('hardware', '0077_alter_requisition_recommended_hod_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hod_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hod_it_profile', verbose_name='Recommended HOD of IT'),
        ),
    ]
