# Generated by Django 3.2.7 on 2024-06-03 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0079_alter_requisition_recommended_hod_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name_plural': 'IT Requisition FORM'},
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Recommended By'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HOD'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hod_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_it_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HOD of IT'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hr_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HR (if Required)'),
        ),
    ]
