# Generated by Django 3.2.7 on 2024-06-03 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0083_alter_requisition_recommended_hod_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hod_it',
            field=models.ManyToManyField(blank=True, related_name='recommended_hod_it_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Recommended HOD of IT'),
        ),
    ]
