# Generated by Django 3.2.7 on 2024-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240603_0946'),
        ('hardware', '0085_alter_requisition_recommended_hod_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='recommended_hod_it',
            field=models.ManyToManyField(blank=True, related_name='recommended_hod_it_requisitions', to='users.Profile', verbose_name='Recommended HODs of IT'),
        ),
    ]
