# Generated by Django 3.2.7 on 2024-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0088_auto_20240619_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionasset',
            name='asset_no',
        ),
    ]
