# Generated by Django 3.2.7 on 2024-06-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0089_remove_requisitionasset_asset_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequisitionAsset',
        ),
    ]
