# Generated by Django 3.2.7 on 2024-06-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0091_alter_requisitionacc_requisition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name_plural': 'IT Requisition Forms'},
        ),
        migrations.AlterField(
            model_name='requisitionacc',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_acc', to='hardware.requisition'),
        ),
        migrations.CreateModel(
            name='RequisitionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=100, unique=True, verbose_name='Asset No')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_asset', to='hardware.requisition')),
            ],
        ),
    ]
