# Generated by Django 3.2.7 on 2024-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0092_auto_20240619_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_asset_no',
            field=models.BooleanField(default=False),
        ),
    ]
