# Generated by Django 3.2.7 on 2024-06-24 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0094_auto_20240620_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_requisitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
