# Generated by Django 3.2.7 on 2024-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0096_alter_requisition_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transfer_list_item',
            field=models.BooleanField(default=False),
        ),
    ]
