# Generated by Django 3.2.7 on 2024-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0098_auto_20240901_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='has_asset_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='transfer_list_item',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
