# Generated by Django 3.2.7 on 2024-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0099_auto_20240901_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requisition_attachment',
            field=models.FileField(blank=True, null=True, upload_to='Requisition_attachment/', verbose_name='Requisition Attachment'),
        ),
    ]
