# Generated by Django 3.2.7 on 2024-12-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0104_historicalcostcenter_historicalproduct_historicalproductmodel_historicalrequisitionacc_historicalreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.productmodel'),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='unit_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.quantityunit', verbose_name='Unit Type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.productmodel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.quantityunit', verbose_name='Unit Type'),
        ),
    ]
