# Generated by Django 3.1.7 on 2021-04-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_activation', multiselectfield.db.fields.MultiSelectField(choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=100)),
                ('mail_activation', multiselectfield.db.fields.MultiSelectField(choices=[('ms_Outlook', 'Outlook'), ('outgoing_permission', 'Outgoing Permission'), ('webmail', 'Webmail Access'), ('Mail_access_from_phone', 'Mail Access from Phone')], max_length=100)),
                ('approved_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hod', to=settings.AUTH_USER_MODEL)),
                ('approved_hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hr', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('approved_hod', 'Approved by HOD'), ('approved_hr', 'Approved by HR')], default='Recommendation', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sign', to='blog.account')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('mailbox_size', models.IntegerField(default=300)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_it', to='blog.account')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
