# Generated by Django 3.2.6 on 2021-09-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='supervisor',
        ),
    ]
