# Generated by Django 3.2.7 on 2021-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_account_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsign',
            name='sign_type',
            field=models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
    ]
