# Generated by Django 3.2.7 on 2021-10-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_accountit_mailbox_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountit',
            name='user_mail',
        ),
    ]
