# Generated by Django 3.2.7 on 2021-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_accountit_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountit',
            name='admin_comment',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
