# Generated by Django 3.2.7 on 2021-11-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_historicalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountit',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_it', to='blog.account'),
        ),
    ]
