# Generated by Django 3.2.7 on 2021-12-11 08:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_historicalprofile'),
        ('blog', '0011_alter_accountit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_join_date', models.DateField(default=datetime.date.today)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_activation', multiselectfield.db.fields.MultiSelectField(choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=100)),
                ('mail_activation', multiselectfield.db.fields.MultiSelectField(choices=[('ms_Outlook', 'Outlook'), ('outgoing_permission', 'Outgoing Permission'), ('webmail', 'Webmail Access'), ('Mail_access_from_phone', 'Mail Access from Phone')], max_length=100)),
                ('approved_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hod_emp', to=settings.AUTH_USER_MODEL)),
                ('approved_hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hr_emp', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.position')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.floor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location')),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_emp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('agreed', 'Agreed'), ('disagreed', 'Disagreed')], default='Agreed', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sign', to='blog.employee')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.EmailField(max_length=100)),
                ('mail_box', models.IntegerField(default=300)),
                ('admin_comment', models.CharField(max_length=250)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_it', to='blog.employee')),
            ],
        ),
    ]
