# Generated by Django 3.2.7 on 2021-12-20 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0059_auto_20211220_1714'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_employee_employeeit_employeesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_data', models.CharField(choices=[('transferred', 'Transferred'), ('destroyed', 'Destroyed')], default='Transferred', max_length=30)),
                ('common_computer_ip', models.BooleanField()),
                ('ip_phone', models.CharField(max_length=10)),
                ('common_ip_phone', models.BooleanField()),
                ('printer_owner', models.BooleanField()),
                ('scanner_owner', models.BooleanField()),
                ('internet_access', models.BooleanField()),
                ('empower_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chromeleon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('eqms_id', models.CharField(blank=True, max_length=50, null=True)),
                ('standalone_id', models.CharField(blank=True, max_length=252, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('computer_data_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_data_receiver', to=settings.AUTH_USER_MODEL)),
                ('computer_ip_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_ip_address', to='connectivity.lan')),
                ('computer_ip_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_ip_receiver', to=settings.AUTH_USER_MODEL)),
                ('email_archive_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_archive_receiver', to=settings.AUTH_USER_MODEL)),
                ('ip_phone_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_phone_receiver', to=settings.AUTH_USER_MODEL)),
                ('printer_receiever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_receiver', to=settings.AUTH_USER_MODEL)),
                ('scanner_receiever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
