# Generated by Django 3.2.7 on 2021-12-21 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_resignation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Account Modification FORM'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'HR: Employee Activation FORM'},
        ),
        migrations.AlterModelOptions(
            name='resignation',
            options={'verbose_name_plural': 'IT Release FORM'},
        ),
        migrations.AddField(
            model_name='resignation',
            name='recommended_hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hod_resignation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResignationSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_area', multiselectfield.db.fields.MultiSelectField(choices=[('computer_data', 'Computer Data'), ('email_archive', 'Email Archived'), ('computer_ip', 'Computer IP'), ('ip_phone', 'IP Phone'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('internet_access', 'Internet Access'), ('empower_id', 'Empower ID'), ('chromeleon_id', 'Chroemeleon ID'), ('eqms_id', 'EQMS ID'), ('standalone_id', 'Standalone ID'), ('email_disable', 'Email ID Disable'), ('primary_sign', 'Primary IT sign (After Disaled Email ID)'), ('email_deletion', 'Email ID Deletetion'), ('final_sign', 'Final IT sign (After Deleted Email ID)')], max_length=100)),
                ('comment', models.CharField(choices=[('received', 'I have recieved.'), ('disabled', 'I have disabled (only for IT).'), ('reviewed', 'I have reviewed (only for IT).'), ('deleted', 'I have deleted (only for IT).')], default='I have recieved.', max_length=50)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_sign', to='blog.resignation')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
