# Generated by Django 3.2.7 on 2021-12-22 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211221_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
