# Generated by Django 3.2.7 on 2022-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_resignation_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='email_archive',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Completed', max_length=30),
        ),
    ]
