# Generated by Django 3.2.7 on 2022-01-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_resignationsign_signing_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationsign',
            name='comment',
            field=models.CharField(choices=[('Received', 'I have recieved.'), ('Reviewed', 'I have reviewed.'), ('Disabled', 'I have disabled (only for IT).'), ('Deleted', 'I have deleted (only for IT).')], default='I have recieved.', max_length=50),
        ),
    ]
