# Generated by Django 3.2.7 on 2022-01-04 18:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_resignationsign_signing_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationsign',
            name='signing_area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('computer_data', 'Computer Data'), ('email_archive', 'Email Archived'), ('computer_ip', 'Computer IP'), ('ip_phone', 'IP Phone'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('recommended_hod', 'Recommended HOD'), ('internet_access', 'Internet Access'), ('empower_id', 'Empower ID'), ('chromeleon_id', 'Chroemeleon ID'), ('eqms_id', 'EQMS ID'), ('standalone_id', 'Standalone ID'), ('email_disable', 'Email ID Disable'), ('primary_sign', 'Primary IT sign (After Disaled Email ID)'), ('email_deletion', 'Email ID Deletion'), ('final_sign', 'Final IT sign (After Deleted Email ID)')], max_length=196),
        ),
    ]
