# Generated by Django 3.2.7 on 2022-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20220626_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
    ]
