# Generated by Django 3.2.7 on 2022-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_historicalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
