# Generated by Django 3.2.7 on 2022-07-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_accountsign_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accountsign',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_sign', to='blog.account'),
        ),
        migrations.AlterField(
            model_name='accountsign',
            name='sign_type',
            field=models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50),
        ),
    ]
