# Generated by Django 3.2.7 on 2022-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220713_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeeit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeesign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
