# Generated by Django 3.2.7 on 2022-07-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20220713_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesign',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
