# Generated by Django 3.2.7 on 2022-07-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_employeesign_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesign',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sign', to='blog.employee'),
        ),
    ]
