# Generated by Django 3.2.7 on 2022-07-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_employeesign_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeehod',
            old_name='account',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeehr',
            old_name='account',
            new_name='employee',
        ),
    ]
