# Generated by Django 3.2.7 on 2022-07-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20220713_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Agreed', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resignation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ResignationSign',
        ),
        migrations.AddField(
            model_name='resignationdata',
            name='resignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_data', to='blog.resignation'),
        ),
        migrations.AddField(
            model_name='resignationdata',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
