# Generated by Django 3.2.7 on 2022-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_resignation_ip_phone_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='ip_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
