# Generated by Django 3.2.7 on 2022-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_resignation_ip_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
