# Generated by Django 3.2.7 on 2022-08-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_accountit_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Mail Account Creation FORM'},
        ),
    ]
