# Generated by Django 3.2.7 on 2024-05-01 02:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group_access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dhaka_unit', 'SPL Dhaka Unit'), ('dhaka_unit_management', 'SPL Dhaka Unit Management'), ('dhaka_unit_managers', 'SPL Dhaka Unit Managers')], max_length=100, null=True),
        ),
    ]
