# Generated by Django 3.2.7 on 2024-05-01 02:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_employee_group_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group_access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dhaka_unit', 'SPL Dhaka Unit'), ('dhaka_unit_management', 'SPL Dhaka Unit Management'), ('dhaka_unit_managers', 'SPL Dhaka Unit Managers')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mail_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Outlook'), ('outgoing_permission', 'Outgoing Permission'), ('webmail', 'Webmail Access'), ('Mail_access_from_phone', 'Mail Access from Phone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_activation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=100),
        ),
    ]
