# Generated by Django 3.2.7 on 2024-05-01 02:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20240501_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=100, null=True),
        ),
    ]
