# Generated by Django 3.2.7 on 2024-05-29 11:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20240501_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mail_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=100, null=True),
        ),
    ]
