# Generated by Django 3.2.7 on 2024-06-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0042_employee_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='approved_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hr_emp', to=settings.AUTH_USER_MODEL),
        ),
    ]
