# Generated by Django 3.2.7 on 2024-07-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0044_auto_20240627_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='approved_hr',
        ),
        migrations.AddField(
            model_name='account',
            name='approved_hr',
            field=models.ManyToManyField(blank=True, related_name='approved_hr', to=settings.AUTH_USER_MODEL, verbose_name='Approved HR'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group_access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dhaka_unit', 'SPL Dhaka Unit'), ('dhaka_unit_management', 'SPL Dhaka Unit Management'), ('dhaka_unit_managers', 'SPL Dhaka Unit Managers')], max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_activation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=40, null=True),
        ),
    ]
