# Generated by Django 3.2.7 on 2024-12-19 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0102_alter_switch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_auto_20241214_1308'),
        ('blog', '0045_auto_20240707_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResignation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('computer_data', models.CharField(choices=[('transferred', 'Transferred'), ('destroyed', 'Destroyed')], default='Transferred', max_length=30)),
                ('email_archive', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Completed', max_length=30)),
                ('common_computer_ip', models.BooleanField()),
                ('ip_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('common_ip_phone', models.BooleanField()),
                ('printer_owner', models.BooleanField()),
                ('scanner_owner', models.BooleanField()),
                ('internet_access', models.BooleanField()),
                ('empower_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chromeleon_id', models.CharField(blank=True, max_length=50, null=True)),
                ('eqms_id', models.CharField(blank=True, max_length=50, null=True)),
                ('standalone_id', models.CharField(blank=True, max_length=252, null=True)),
                ('date_posted', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('computer_data_receiver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('computer_ip_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='connectivity.lan')),
                ('computer_ip_receiver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('email_archive_receiver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ip_phone_receiver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer_receiever', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recommended_hod', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scanner_receiever', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical resignation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_join_date', models.DateField(default=datetime.date.today)),
                ('phone', models.CharField(max_length=15)),
                ('ext', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.TextField(default='default.jpg', max_length=100)),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('user_activation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=40, null=True)),
                ('mail_activation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=61, null=True)),
                ('group_access', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dhaka_unit', 'SPL Dhaka Unit'), ('dhaka_unit_management', 'SPL Dhaka Unit Management'), ('dhaka_unit_managers', 'SPL Dhaka Unit Managers')], max_length=52, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_hod', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.department')),
                ('designation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.position')),
                ('floor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.floor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.location')),
                ('recommended_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('justification', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('user_activation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('computer_login_access', 'Computer Login Access'), ('file_printer_share', 'File & Printer Sharing')], max_length=100, null=True)),
                ('mail_activation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ms_Outlook', 'Microsoft Outlook'), ('outgoing_permission', 'Outgoing Permission (Gmail, Other Company Mail)'), ('webmail', 'Webmail (Access from Chrome/Firefox through internet)'), ('Mail_access_from_phone', 'Mail Access from Mobile Phone')], max_length=100, null=True)),
                ('group_access', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dhaka_unit', 'SPL Dhaka Unit'), ('dhaka_unit_management', 'SPL Dhaka Unit Management'), ('dhaka_unit_managers', 'SPL Dhaka Unit Managers')], max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_hod', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
