# Generated by Django 3.2.7 on 2024-12-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_historicalaccount_historicalemployee_historicalresignation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemployee',
            name='approved_hod',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='computer_data_receiver',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='computer_ip_address',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='computer_ip_receiver',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='email_archive_receiver',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='ip_phone_receiver',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='printer_receiever',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='recommended_hod',
        ),
        migrations.RemoveField(
            model_name='historicalresignation',
            name='scanner_receiever',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
        migrations.DeleteModel(
            name='HistoricalResignation',
        ),
    ]
