# Generated by Django 3.2.7 on 2024-12-23 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_historicaltracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltracker',
            name='description',
            field=ckeditor.fields.RichTextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=ckeditor.fields.RichTextField(default='No description'),
        ),
    ]
