# Generated by Django 3.2.7 on 2024-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20241223_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltracker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
