# Generated by Django 3.1.7 on 2021-04-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reference_form', models.CharField(blank=True, max_length=30, null=True)),
                ('problem_category', models.CharField(choices=[('Hardware', 'Hardware Related'), ('Software', 'Software Related'), ('File/Printer Sharing', 'File & Printer Sharing'), ('Email/Internet', 'Email/Internet Related'), ('IP Phone', 'IP Phone Related'), ('Network/Lan', 'Network/Lan Related'), ('Audio/Video Conference', 'Audio & Video Conference'), ('Empower/Chromeleon', ' Empower & Chromeleon Related'), ('LIMS_EQMS/TRIMS', 'LIMS (EQMS/TRIMS)'), ('Standalone System', 'Standalone System'), ('Other', 'Other')], max_length=50)),
                ('problem_description', models.TextField()),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('ticket_raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_raiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_type', models.CharField(choices=[('working', 'Working'), ('solved', 'Solved'), ('closed', 'Closed')], default='Working', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('problem_solution', models.TextField(default='done')),
                ('date_solved', models.DateTimeField(auto_now_add=True)),
                ('eticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_solve', to='ticket.eticket')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.TextField()),
                ('date_discussed', models.DateTimeField(auto_now_add=True)),
                ('discusser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusser', to=settings.AUTH_USER_MODEL)),
                ('eticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_discuss', to='ticket.eticket')),
            ],
        ),
        migrations.CreateModel(
            name='EAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_type', models.CharField(choices=[('assigned', 'Assigned'), ('forwarding', 'Forwarding')], default='Assigned', max_length=50)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL)),
                ('eticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_assign', to='ticket.eticket')),
            ],
        ),
    ]
