# Generated by Django 3.2.7 on 2021-10-03 12:00

from django.db import migrations

def fill_problem_category_fk(apps, schema_editor):
  Eticket = apps.get_model('ticket', 'Eticket')
  ProblemCategory = apps.get_model('ticket', 'ProblemCategory')
  for eticket in Eticket.objects.all():
    eticket.problem_category_fk, created = ProblemCategory.objects.get_or_create(problem_name=eticket.problem_category)
    eticket.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20211003_1156'),
    ]

    operations = [
        migrations.RunPython(fill_problem_category_fk)
    ]
