# Generated by Django 3.2.7 on 2021-10-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20211003_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticket',
            name='problem_category',
        ),
        migrations.RenameField(
            model_name='eticket',
            old_name='problem_category_fk',
            new_name='problem_category'
        ),
    ]
