# Generated by Django 3.2.7 on 2021-10-03 13:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20211003_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
