# Generated by Django 3.2.7 on 2022-02-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_eticket_problem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esolve',
            name='problem_solution',
        ),
        migrations.AlterField(
            model_name='esolve',
            name='eticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_solve', to='ticket.eticket'),
        ),
    ]
