# Generated by Django 3.2.7 on 2022-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_esolve_solve_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esolve',
            name='solve_type',
            field=models.CharField(choices=[('solved', 'Solved'), ('closed', 'Closed')], default='SOlved', max_length=20),
        ),
    ]
