# Generated by Django 3.2.7 on 2022-07-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_alter_esolve_solve_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.TextField()),
                ('date_discussed', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_admin', to=settings.AUTH_USER_MODEL)),
                ('eticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_internal', to='ticket.eticket')),
            ],
        ),
    ]
