# Generated by Django 3.2.7 on 2022-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_esolve_solve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
