# Generated by Django 3.2.7 on 2022-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_eticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
