# Generated by Django 3.2.7 on 2024-07-10 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0013_eticket_ticket_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='ticket_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineered_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='ticket_raiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
