# Generated by Django 3.2.7 on 2024-07-10 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0014_auto_20240710_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='ticket_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='ticket_raiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_raiser', to=settings.AUTH_USER_MODEL),
        ),
    ]
