# Generated by Django 3.2.7 on 2024-07-10 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20240710_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
