# Generated by Django 3.2.7 on 2024-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_alter_eticket_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
