# Generated by Django 3.2.7 on 2024-09-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_eticket_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eticket',
            old_name='link',
            new_name='form_link',
        ),
    ]
