# Generated by Django 3.2.7 on 2024-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_rename_link_eticket_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='created_via',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
    ]
