# Generated by Django 3.2.7 on 2024-12-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('RESOLVE', 'Resolve'), ('COMMENT', 'Comment'), ('MESSAGE', 'Message')], max_length=20),
        ),
    ]
