# Generated by Django 3.2.7 on 2024-12-19 12:40

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_historicalaudittrail_historicaleassign_historicalediscussion_historicaleinternal_historicalesolve_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='eticket_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/eticket/', validators=[ticket.models.validate_file_size], verbose_name='Eticket Attachment'),
        ),
    ]
