# Generated by Django 3.2.7 on 2024-12-19 12:45

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_eticket_eticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='eticket_attachment',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.eticket_attachment_upload_path, validators=[ticket.models.validate_file_size], verbose_name='Eticket Attachment'),
        ),
    ]
