# Generated by Django 3.2.7 on 2024-12-19 13:09

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_alter_eticket_eticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='eticket_attachment',
            field=models.FileField(blank=True, null=True, upload_to='eticket_attachments/', validators=[ticket.models.validate_file_size], verbose_name='Eticket Attachment'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicaleticket',
            name='problem_description',
            field=models.TextField(),
        ),
    ]
