# Generated by Django 3.2.7 on 2024-12-23 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_auto_20241219_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='historicaleticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
