# Generated by Django 3.2.7 on 2024-12-23 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_auto_20241223_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='historicaleticket',
            name='problem_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
